spring:
  banner:
    location: banner/dev.txt
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ddd?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver